from pathlib import Path
import sys

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))
import generate  # noqa: E402


def test_parse_pod_label():
    assert generate.parse_pod_label("app=librechat") == ("app", "librechat")
    with pytest.raises(ValueError):
        generate.parse_pod_label("noequals")


def test_file_sha_stable_and_absent(tmp_path):
    p = tmp_path / "f.txt"
    p.write_text("hello")
    sha = generate.file_sha(p)
    assert len(sha) == 12 and sha == generate.file_sha(p)
    assert generate.file_sha(None) == "absent"
    assert generate.file_sha(tmp_path / "missing") == "absent"


def test_render_policy_structure():
    result = generate.ResolveResult(
        groups=[
            generate.DomainGroup("always_on: image_registry", ["registry.librechat.ai"]),
            generate.DomainGroup("bedrock runtime", ["bedrock-runtime.us-east-1.amazonaws.com"]),
        ],
        notes=["(skipped internal MCP foo: http://host.docker.internal:3001/mcp)"],
        warnings=[],
        has_subprocess_mcp=False,
    )
    out = generate.render_policy(
        result, namespace="librechat", pod_label=("app", "librechat"),
        config_sha="abc123abc123", env_sha="absent",
    )
    assert out.startswith("# Generated by utils/egress-policy/generate.py\n")
    assert "# Source: librechat.yaml (sha: abc123abc123), .env (sha: absent)" in out
    assert "# DO NOT EDIT" in out
    assert "apiVersion: networking.aviatrix.com/v1alpha1" in out
    assert "kind: FirewallPolicy" in out
    assert "namespace: librechat" in out
    assert "          app: librechat" in out  # matchLabels indentation
    assert "        # --- always_on: image_registry ---" in out
    assert '        - "registry.librechat.ai"' in out
    assert "        # --- bedrock runtime ---" in out
    assert "      # notes:" in out
    assert "      # (skipped internal MCP foo: http://host.docker.internal:3001/mcp)" in out
    assert out.endswith("\n")


def test_render_policy_empty_groups_is_valid():
    result = generate.ResolveResult(groups=[], notes=[], warnings=[], has_subprocess_mcp=False)
    out = generate.render_policy(
        result, namespace="librechat", pod_label=("app", "librechat"),
        config_sha="x", env_sha="absent",
    )
    assert "      domains:" in out
    assert "# (no domains resolved" in out
    assert out.endswith("\n")


def test_render_includes_default_deny_by_default():
    result = generate.ResolveResult(
        groups=[generate.DomainGroup("always_on: image_registry", ["registry.librechat.ai"])],
        notes=[], warnings=[], has_subprocess_mcp=False,
    )
    out = generate.render_policy(
        result, namespace="librechat", pod_label=("app", "librechat"),
        config_sha="x", env_sha="absent",
    )
    assert "- name: deny-other-egress" in out
    assert "action: deny" in out
    # permit rule comes before the deny rule (first-match ordering)
    assert out.index("allow-librechat-egress") < out.index("deny-other-egress")


def test_render_no_default_deny_omits_rule():
    result = generate.ResolveResult(
        groups=[generate.DomainGroup("always_on: image_registry", ["registry.librechat.ai"])],
        notes=[], warnings=[], has_subprocess_mcp=False,
    )
    out = generate.render_policy(
        result, namespace="librechat", pod_label=("app", "librechat"),
        config_sha="x", env_sha="absent", default_deny=False,
    )
    assert "deny-other-egress" not in out
    assert "action: deny" not in out
